version: "3.7"
services:
  rancher:
    image: rancher/rancher:v2.5.1
    volumes: 
      - ./rancher:/var/lib/rancher
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=<example.com>
      - LETSENCRYPT_HOST=<example.com>
      - LETSENCRYPT_EMAIL=<example@gmail.com>
    restart: unless-stopped
    privileged: true

networks:
  default:
    external:
      name: nginx-proxy

